kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: iris-seldon
  labels:
    app: iris-seldon
    app.kubernetes.io/component: iris-seldon
    app.kubernetes.io/instance: iris-seldon
    app.kubernetes.io/name: iris-seldon
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'iris-seldon:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.8-ubi7'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/strangiato/Iris_seldon.git'
    contextDir: iris-seldon-service
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
