apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: iris-seldon
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /prometheus
      targetPort: metrics
  selector:
    matchLabels:
      seldon-app: iris-seldon-example