apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: iris-seldon
spec:
  name: test-deployment-iris
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - image: >-
                  image-registry.openshift-image-registry.svc:5000/honda/iris-seldon
                name: classifier
                ports:
                  - containerPort: 6000
                    name: metrics
                    protocol: TCP
      graph:
        children: []
        endpoint:
          service_host: localhost
          service_port: 9000
          type: REST
        name: classifier
        type: MODEL
      name: example
      replicas: 1
  replicas: 1
