apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: iris-seldon
spec:
  endpoints:
    - interval: 30s
      path: /prometheus
      port: http
  selector:
    matchLabels:
      seldon-app: iris-seldon-example
